export const POINT_TYPES = {
  SIGNUP: 'SIGNUP',
  DOS: 'DOS',
  DAILY_ATTENDANCE: 'DAILY_ATTENDANCE',
  CONSECUTIVE_ATTENDANCE_BONUS: 'CONSECUTIVE_ATTENDANCE_BONUS',
  PARTY_VOTE: 'PARTY_VOTE',
  BALANCE_GAME: 'BALANCE_GAME',
};

export const POINT_TYPE_DESCRIPTIONS = {
  [POINT_TYPES.SIGNUP]: '회원가입 완료',
  [POINT_TYPES.DOS]: 'DOS 검사 완료',
  [POINT_TYPES.DAILY_ATTENDANCE]: '일일 출석',
  [POINT_TYPES.CONSECUTIVE_ATTENDANCE_BONUS]: '연속 출석 보너스',
  [POINT_TYPES.PARTY_VOTE]: '정당 지지',
  [POINT_TYPES.BALANCE_GAME]: '밸런스 게임 참여',
};
